/**
 * Generated by Gas3 v2.3.2 (Granite Data Services).
 *
 * NOTE: this file is only generated if it does not exist. You may safely put
 * your custom code here.
 */

package org.example.entities {

    [Bindable]
    [RemoteClass(alias="org.example.entities.Welcome")]
    public class Welcome extends WelcomeBase {
    }
}